sudo: true

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: v2.0.0

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec app python -m pytest app/tests

after_script:
  - docker-compose down