version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: fasthabr_api
      POSTGRES_PASSWORD: root
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-32700}:5432